name: flutter_calendar_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.12
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  date_time_picker: ^1.0.1
  modal_progress_hud: ^0.1.3
  loading_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
