name: flutter_calender
description: Edit your google calender with this app in simpler way.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# Some of these dependencies might not be used in project
#
# TODO : Final package shrinking should be done (its done)

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  get_it: ^5.0.0
  equatable: ^1.2.5
  dartz: ^0.9.1
  flutter_bloc: ^6.0.5
  http: ^0.12.2
  connectivity: ^0.4.9+2

  googleapis: ^0.55.0
  # this package is dum it uses web auth on mobile :|
  # I can do better with google_sign_in :). AND I DID.
  googleapis_auth: ^0.2.12
  google_sign_in: ^4.5.3
  intl: ^0.16.1


# Some of these dev_dependencies might not be used in project
#
# No shrinking needed since these are only for developing
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.4.1
  mockito: ^4.1.1
  intl_translation: ^0.17.10+1

flutter:

  uses-material-design: true
